from interfaces.plant import ITerrestrial
from interfaces.plant import IAquatic
from interfaces.animal import IFlying
from interfaces.animal import IFreshwater
from interfaces.animal import IWalking
from interfaces.animal import ISwimming
from interfaces.animal import ISaltwater
from interfaces.identifiable import Identifiable
from interfaces.habitat import IContainsAnimals
from interfaces.habitat import IContainsPlants
from interfaces.diet import IEatFish
from interfaces.diet import IEatInsects
from interfaces.diet import IEatRodents
from interfaces.diet import IEatVegetation
from interfaces.lives_in import ICoastline
from interfaces.lives_in import IForest
from interfaces.lives_in import IGrassland
from interfaces.lives_in import IMountain
from interfaces.lives_in import IRiver
from interfaces.lives_in import ISwamp

